### ISSUE TITLE
Compiler (gcc 10.1.0) warning in: src/cmd/collide2/CSopcodecollider.cpp

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#225]
I'm poking through the compiler errors in the compile log, to see if we can tidy things up a little.
This is the very first one in the log, and from the looks of it, it is not so trivial:

[1st_error.docx](https://github.com/vegastrike/Vega-Strike-Engine-Source/files/5027049/1st_error.docx)

**Comment by evertvorster** [comment]
From what I can gather, this behavior is unspecified, but it used to be tolerated by previous versions of GCC.

This comment on StackOverflow says it could cause a double deallocation, which I seem to remember us battling with recently when buying ships:
https://stackoverflow.com/questions/52436264/google-sparsehash-uses-realloc-on-type-which-is-not-trivially-copyable

**Comment by evertvorster** [comment]
[ 10%] Building CXX object CMakeFiles/OPcollide.dir/src/cmd/collide2/CSopcodecollider.cpp.o 
In file included from /home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/collide2/CSopcodecollider.h:34, 
����������������from /home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/collide2/CSopcodecollider.cpp:26: 
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/collide2/CSopcodecollider.cpp: In member function 'void __pairs::SetLimit(int)': 
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/collide2/opcodegarray.h:38:66: warning: 'void* realloc(void*, size_t)' moving an object of non
-trivially copyable type '__pairs::ga_type' {aka 'struct csCollisionPair'}; use 'new' and 'delete' instead [-Wclass-memaccess] 

The offending bit of code is in engine/src/cmd/collide2/opcodegarray.h:38:66
So, why is there code in a header file?

**Comment by BenjamenMeyer** [comment]
@evertvorster yes, this will probably be a harder one to solve.

> why is there code in a header file?

Because some times folks have found it easier to toss code in there. This is usually done for for small inline functions and C/C++ Preprocessor macros; though often C++ Templates get tossed solely into a header too. If it's more than just a getter/setter, or simple 1-2 line inline function then it should be moved to an implementation file instead.

In this case it looks like it's a C Preprocessor macro defining a class. It probably should be converted to a C++ template class.

Is this the line:
https://github.com/vegastrike/Vega-Strike-Engine-Source/blob/master/engine/src/cmd/collide2/opcodegarray.h#L38

It may be saying that it's not wise to reallocate that structure and something else needs to be done instead. It'll probably require a larger design change.
