### ISSUE TITLE
CMake: Don't override usual Debug/Release optimization settings with `BUILD_OPT` by default

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#694]
As it stands currently, `BUILD_OPT` has a default value, and that value is `-O2`. This overrides the usual gcc optimization setting for Debug, which would be `-Og`. This effectively nullifies the Debug/Release distinction, to a large degree.

I am proposing to comment out `BUILD_OPT` until we have a better solution. The eventual solution might be to use [CMake Presets](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html).

**Comment by BenjamenMeyer** [comment]
yeah, I want to take a hard look at the CMake stuff at some point, even start breaking it down to use file globs and be more spread across the directories instead of all in one place. There's advantages both ways; and draw backs both ways. We're probably at the point now where we can drop most of the architecture specific stuff that's there.
