### ISSUE TITLE
SPEC range from planets have changed between engine versions

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#864]
Hi there!

In version 0.8.x of the game engine, I can use SPEC up to nearly 1000 km from Atlantis. 
When starting a new game, you pop up around 1000km from the planet surface, where Oswald comes closer to have a chat. 

In version 0.9.x of the game engine, you are dropped at 10000 km from the planet surface when you launch. Unfortunately, you still need to get to 990km from the surface before you can dock with the planet. SPEC also does not work at this range in the 0.9.x version of the game engine, which means it takes an eternity to get close enough to the planet to dock, and burns quite a bit of fuel doing it. 

One other thing that is missing is the distance to dock indicator. 
I'll stick in a video comparing the two engines so you can see what I am talking about.

**Comment by evertvorster** [comment]
This could be down to a broken save game. I'll make a separate bug report for that now.

**Comment by evertvorster** [comment]
Yes, this is definitely due to the corruption in the save game with an original Llama. Once that is fixed, this should be fixed as well.

**Comment by BenjamenMeyer** [comment]
interesting relationships; though I do run into this from time to time myself where I load a game and it pops me into orbit instead of on the planet.

**Comment by royfalk** [comment]
> interesting relationships; though I do run into this from time to time myself where I load a game and it pops me into orbit instead of on the planet.

The load into space is a separate bug that I've noticed myself and existed since forever really.
The distance to dock is another bug that annoys me. When you get close to a planet dock, it stops counting down and just disappears.
The whole SPEC is unusable around planets is a third, playability bug. It's annoying to be in a gravity well for 20 minutes. It's a game, not real life.

I'm touching the code near the last two and will probably fix them on the way. I'll open a bug for all three. Closing this one.
