### ISSUE TITLE
Save Games with the starting Llama are corrupt in 0.9.x

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#865]
This is a pretty serious bug, as one expects this game to be quite a long-running excersize. 
To show one aspect of this bug, start a new campaign. Don't take off, don't do anything but save your game, and then load it again. 
On my system, once you load that saved game, you are dropped almost 10000km from Atlantis, and your  yaw controls don't work, and you can't use SPEC to get closer to the planet to land.

If you exit out of VS, and then start it again, and then load the game you saved in the previous bit, you are on Atlantis again, but if you just launch you are again 10000km away from the planet, without yaw controls and a SPEC which misbehaves. 

If, on the other hand you start a new campaign, and don't save, and just take off, you are dropped 9222km from the planet, but now you can use your SPEC drive to get closer to the planet quickly, and your yaw control works.
You can also land and take off multiple times, and all the yaw controls work, but it is only when you load a saved game that the game starts misbehaving.

**Comment by evertvorster** [comment]
Interestingly enough, if you load a saved game that was not make by this latest engine, it works properly. 
Also, I am running a different ship than the initial Llama, so the corruption could be sneaking in when saving and loading the initial Llama, which is a bit special.

**Comment by evertvorster** [comment]
Doing a bit more testing here. 
I have a saved game that was made with a previous version of the engine, and here is it's Llama.csv file:
[Llama.begin.csv](https://github.com/user-attachments/files/15847767/Llama.begin.csv)


I loaded that game, and then saved it as something else, and this is the csv file that is produced:
[Llama.begin.csv](https://github.com/user-attachments/files/15847770/Llama.begin.csv)


With even a cursory glance, I can see that there are huge differences. 

However, if I load a saved game that was made by the previous version of the engine where I was piloting a different ship, and save that, there are almost no differences. 
Before:
[Franklin.hunter.csv](https://github.com/user-attachments/files/15847786/Franklin.hunter.csv)

And after:
[Franklin.hunter.csv](https://github.com/user-attachments/files/15847789/Franklin.hunter.csv)

So, as I mentioned before, the Llama you get in the beginning is special, and it looks like the save game routine does not take that into account.

**Comment by evertvorster** [comment]
One other thing to note is that saved games with the 0.9.x engine is incompatible with the 0.8.x engine. My games saved in Sol in 0.9.x crash the 0.8.x engine when loading them.

**Comment by evertvorster** [comment]
There are some other corruptions in savegames between the two versions of the game engine running on the same Assets:
https://youtu.be/ans6G5iGaJU

**Comment by royfalk** [comment]
I noticed some of this too. 
The issue with spawning far from Atlantis is I think intentional and to improve the fun factor. It gets you out of the gravity well and lets you go to SPEC.
I'm not sure  why the difference between 10k and 9.2k but it seems negligible. 

I've reviewed the save game CSVs and they are mostly identical if not sorted the same. There are only a differences between the two. The new save game adds Attack_preference,  Face_camera, Facets,  unit_role, upgrade_type and root. I added root at some point but the rest are not used.
Also, fuel is 24.99 vs. 25. Light doesn't match. Status is maneuvour (typo).
More to the point, I was hoping the CSV was missing some yaw control figures but this is not the case. There is a corruption somewhere else. I'll do some more digging.

**Comment by royfalk** [comment]
I copied your original CSV into one of my saved games and it works. So it is something with the CSV.

**Comment by evertvorster** [comment]
Thanks for looking into this @royfalk 
As mentioned, the starting Llama is special, to add more flavour to the game. Initially, it's top speed is 120, and that goes up to 125 when you do the first refuel and repair. 

I have the suspicion that the starting Llama is defined a lot like the .milspec and other special versions of stock spacecraft.

**Comment by royfalk** [comment]
So the issue is that the new CSV parsing code (only used for saved games) does not properly handle commas within the textual_description field. It splits it into two, causing the following values to be moved by one (or potentially more).

As a workaround, you can delete the comma from it and it should work. 

The old code also used the much shorter "Venerable LIHW built armed light cargo shuttle" instead of "What can be said of a llama, save for that one is rather less suited to carrying than a mule and not too adept at pulling a plowshare."

I'm not sure why this is the case. I think once you repair your ship, it applies values from llama.stock.

In any case, I'll need to think how to fix this. Either I ditch CSV completely and provide a CSV2JSON utility or maybe something else.

**Comment by evertvorster** [comment]
Yes, quite the decision here. We'll ditch csv someday, but how much work is it to ditch it?

Would it not be much simpler to find out why there is a different piece of text there, and change the source of the text so that there is no comma in a CSV file and then ditch the csv later?

Ultimately, it is up to you. Thanks very very much for looking into this.

**Comment by BenjamenMeyer** [comment]
So I'd like to have a new file format by the time we hit 1.0, but we have not really outlined what that format would be yet and I've got some ideas around what we should do - including using JSON and including using a Zip like format similar to what ODF and Java do. So I think we need some design work there before that path could really be gone down.

In the meantime, I think we do need to fix this for the current CSV system.

**Comment by royfalk** [comment]
See https://github.com/orgs/vegastrike/discussions/877
